version: "1.0"
info:
  model: int-scaffold
packages:
- name: Kvv_2404_FedTestProject
  gitServerName: kvv
  gitUrl: https://github.com/Karthik-V-IBM-10
  gitUsername: Karthik-V-IBM-10
  gitBranch: main
- name: WmJDBCAdapter
  version: 10.3.0.0.34
  wpmServer: https://packages.webmethods.io
  wpmRegistry: licensed
- name: WmSalesforceRESTProvider
  wpmServer: https://packages.webmethods.io
  wpmRegistry: licensed
services:
- serviceName: project.kvv_2404_fedtest.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections:mysql
  packages:
  - name: Kvv_2404_FedTestProject
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: WmSalesforceRESTProvider
    version: 12.0.0.0.11
- serviceName: project.kvv_2404_fedtest.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.operations.actions:TestDBConn
  packages:
  - name: Kvv_2404_FedTestProject
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: WmSalesforceRESTProvider
    version: 12.0.0.0.11
- serviceName: project.kvv_2404_fedtest.WmSalesforceRESTProvider.com_webmethods_cloudstreams_salesforce_rest_v60.connections:rest2404
  packages:
  - name: Kvv_2404_FedTestProject
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: WmSalesforceRESTProvider
    version: 12.0.0.0.11
- serviceName: project.kvv_2404_fedtest.integrations:SIQAAdapterFlow
  packages:
  - name: Kvv_2404_FedTestProject
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: WmSalesforceRESTProvider
    version: 12.0.0.0.11
- serviceName: project.kvv_2404_fedtest.integrations:refdaf
  packages:
  - name: Kvv_2404_FedTestProject
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: WmSalesforceRESTProvider
    version: 12.0.0.0.11
- serviceName: project.kvv_2404_fedtest.referencedata:ref1
  packages:
  - name: Kvv_2404_FedTestProject
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: WmSalesforceRESTProvider
    version: 12.0.0.0.11
configurationVariables:
  jdbc.Embedded-Database-Pool.waitingThread: "0"
  ? artConnection.Kvv_2404_FedTestProject.project.kvv_2404_fedtest.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.mysql.connectionSettings.password
  : "{AES}D6/2AGfsSWDOcWCLrORnEQ=="
  ? cloudstreamsconnection.project..kvv_2404_fedtest..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:rest2404.oauth_v20.authorizationHeaderPrefix
  : Bearer
  jdbcfunc.Xref.failFastMode: true
  jdbcfunc.Xref.connPoolAlias: Embedded-Database-Pool
  jdbc.Embedded-Database-Pool.userid: APP
  jdbcfunc.ISInternal.connPoolAlias: Embedded-Database-Pool
  jdbc.Embedded-Database-Pool.password: "{AES}Zcw2EXTJgNDVmVzJO2Y3Bw=="
  ? artConnection.Kvv_2404_FedTestProject.project.kvv_2404_fedtest.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.mysql.connectionSettings.user
  : siqatest
  ? cloudstreamsconnection.project..kvv_2404_fedtest..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:rest2404.cn.reuseAddr
  : "false"
  ? artConnection.Kvv_2404_FedTestProject.project.kvv_2404_fedtest.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.mysql.connectionManagerSettings.startupBackoffSecs
  : "10"
  jdbc.SAP-TxStore-Pool.userid: root
  ? artConnection.Kvv_2404_FedTestProject.project.kvv_2404_fedtest.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.mysql.connectionSettings.datasourceClass
  : com.mysql.cj.jdbc.MysqlDataSource
  jdbc.SAP-TxStore-Pool.snoopenabled: "false"
  jdbc.Embedded-Database-Pool.snoopparms: ddtdbg.ProtocolTraceEnable=true;ddtdbg.ProtocolTraceMaxline=16;ddtdbg.ProtocolTraceLocation=logs/snoop/Embedded-Database-Pool.log;ddtdbg.ProtocolTraceShowTime=true
  jdbc.Embedded-Database-Pool.maxConns: "10"
  jdbc.SAP-TxStore-Pool.waitingThread: "10"
  jdbc.Embedded-Database-Pool.expireTime: "60000"
  jdbc.Embedded-Database-Pool.useSSL: "false"
  jdbc.Embedded-Database-Pool.driverAlias: Embedded Database Driver
  jdbc.Embedded-Database-Pool.spyparms: SpyAttributes=(log=(file)logs/spy/Embedded-Database-Pool.log;logTName=yes;timestamp=yes)
  ? artConnection.Kvv_2404_FedTestProject.project.kvv_2404_fedtest.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.mysql.connectionManagerSettings.blockingTimeout
  : "1000"
  jdbc.Embedded-Database-Pool.dbURL: jdbc:derby:embedded;create=true
  jdbc.SAP-TxStore-Pool.useSSL: "false"
  ? cloudstreamsconnection.project..kvv_2404_fedtest..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:rest2404.oauth_v20.authenticationServerUrl
  : https://login.salesforce.com/services/oauth2/token
  ? cloudstreamsconnection.project..kvv_2404_fedtest..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:rest2404.oauth_v20.authorizationServerUrl
  : https://login.salesforce.com/services/oauth2/authorize
  jdbcfunc.SAPTxStore.connPoolAlias: SAP-TxStore-Pool
  ? cloudstreamsconnection.project..kvv_2404_fedtest..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:rest2404.cn.sockBuffSize
  : "8192"
  ? artConnection.Kvv_2404_FedTestProject.project.kvv_2404_fedtest.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.mysql.connectionSettings.databaseName
  : MYSQL_DATABASE
  jdbcfunc.ISDashboardStats.failFastMode: false
  ? cloudstreamsconnection.project..kvv_2404_fedtest..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:rest2404.oauth.consumerSecret
  : "{AES}GgpQnyJJ1uL6OsF0eMPiqoqX3ylfQbZjKvciNaa6CHatTyEt6cAu1xYN8BAkAutwj72/uOKYBgByAqSlgRBNqWmK1wuN3U1rA1B0VhuZoUw="
  jdbc.Embedded-Database-Pool.spyenabled: "false"
  ? artConnection.Kvv_2404_FedTestProject.project.kvv_2404_fedtest.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.mysql.connectionManagerSettings.poolable
  : "false"
  ? artConnection.Kvv_2404_FedTestProject.project.kvv_2404_fedtest.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.mysql.connectionSettings.portNumber
  : "3306"
  jdbc.SAP-TxStore-Pool.poolThreshold: "0"
  ? artConnection.Kvv_2404_FedTestProject.project.kvv_2404_fedtest.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.mysql.connectionSettings.otherProperties
  : loginTimeout=60;driverType=thin;
  jdbc.SAP-TxStore-Pool.expireTime: "60000"
  ? artConnection.Kvv_2404_FedTestProject.project.kvv_2404_fedtest.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.mysql.connectionSettings.transactionType
  : NO_TRANSACTION
  ? cloudstreamsconnection.project..kvv_2404_fedtest..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:rest2404.cn.tcpNoDelay
  : "false"
  ? cloudstreamsconnection.project..kvv_2404_fedtest..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:rest2404.cn.retryIfRequestSentOk
  : "true"
  jdbc.SAP-TxStore-Pool.description: Connection Pool for the SAP Transaction Store
  ? cloudstreamsconnection.project..kvv_2404_fedtest..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:rest2404.cn.socketLinger
  : "-1"
  jdbc.Embedded-Database-Pool.poolThreshold: "0"
  ? cloudstreamsconnection.project..kvv_2404_fedtest..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:rest2404.cn.idleTimeout
  : "-1"
  jdbc.SAP-TxStore-Pool.password: "{AES}nrGf3u7Wt20hFBGh5ZeEuQ=="
  ? cloudstreamsconnection.project..kvv_2404_fedtest..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:rest2404.cx.grant_type
  : refresh_token
  ? cloudstreamsconnection.project..kvv_2404_fedtest..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:rest2404.connectionEnabled
  : "true"
  ? cloudstreamsconnection.project..kvv_2404_fedtest..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:rest2404.oauth.accessToken
  : "{AES}7vZbWzyLRu2KZ5z191Zgwdr7/M+VfooozU57fC//O0ikGXDPP9dcYFAP6hjx2hgHQwlw6t+LVXL+gQZY/wWbUSK56iGb8pWddJ7MN1MVFstd27Uq2ZW9gko3I9DG/1XsjyscsfT0k2Iic2CULRlbRWmK1wuN3U1rA1B0VhuZoUw="
  ? cloudstreamsconnection.project..kvv_2404_fedtest..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:rest2404.oauth_v20.authorizationHeaderInTokenRefresh
  : "false"
  jdbc.SAP-TxStore-Pool.driverAlias: MySQL CC Driver
  ? artConnection.Kvv_2404_FedTestProject.project.kvv_2404_fedtest.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.mysql.connectionSettings.trustStore
  : ""
  ? artConnection.Kvv_2404_FedTestProject.project.kvv_2404_fedtest.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.mysql.connectionManagerSettings.startupRetryCount
  : "0"
  jdbc.SAP-TxStore-Pool.snoopparms: ddtdbg.ProtocolTraceEnable=true;ddtdbg.ProtocolTraceMaxline=16;ddtdbg.ProtocolTraceLocation=logs/snoop/SAP-TxStore-Pool.log;ddtdbg.ProtocolTraceShowTime=true
  ? artConnection.Kvv_2404_FedTestProject.project.kvv_2404_fedtest.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.mysql.connectionSettings.networkProtocol
  : tcp
  ? artConnection.Kvv_2404_FedTestProject.project.kvv_2404_fedtest.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.mysql.connectionSettings.keyStore
  : ""
  jdbcfunc.SAPTxStore.failFastMode: false
  ? artConnection.Kvv_2404_FedTestProject.project.kvv_2404_fedtest.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.mysql.connectionSettings.serverName
  : 9.46.196.248
  jdbcfunc.ISDashboardStats.connPoolAlias: Embedded-Database-Pool
  jdbc.SAP-TxStore-Pool.dbURL: jdbc:mysql://localhost:3306/SAPTRANSACTIONSTORE?useSSL=false&characterEncoding=utf-8&autoReconnect=true&maxReconnects=5&sessionVariables=wait_timeout=2147483
  ? cloudstreamsconnection.project..kvv_2404_fedtest..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:rest2404.cn.hostnameVerifier
  : org.apache.http.conn.ssl.DefaultHostnameVerifier
  ? cloudstreamsconnection.project..kvv_2404_fedtest..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:rest2404.cn.keepAliveInterval
  : "300000"
  ? cloudstreamsconnection.project..kvv_2404_fedtest..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:rest2404.expireTimeout
  : "1000"
  ? cloudstreamsconnection.project..kvv_2404_fedtest..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:rest2404.oauth_v20.accessTokenRefreshURLRequest
  : URL Query String
  ? cloudstreamsconnection.project..kvv_2404_fedtest..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:rest2404.startupRetryCount
  : "0"
  ? cloudstreamsconnection.project..kvv_2404_fedtest..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:rest2404.cn.validateAfterInactivity
  : "1000"
  ? cloudstreamsconnection.project..kvv_2404_fedtest..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:rest2404.oauth_v20.refreshAccessToken
  : "true"
  ? cloudstreamsconnection.project..kvv_2404_fedtest..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:rest2404.oauth_v20.accessTokenRefreshURL
  : https://login.salesforce.com/services/oauth2/token
  ? artConnection.Kvv_2404_FedTestProject.project.kvv_2404_fedtest.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.mysql.connectionManagerSettings.maximumPoolSize
  : "10"
  ? cloudstreamsconnection.project..kvv_2404_fedtest..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:rest2404.cn.retryCount
  : "4"
  ? artConnection.Kvv_2404_FedTestProject.project.kvv_2404_fedtest.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.mysql.connectionManagerSettings.poolIncrementSize
  : "1"
  ? artConnection.Kvv_2404_FedTestProject.project.kvv_2404_fedtest.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.mysql.connectionManagerSettings.minimumPoolSize
  : "1"
  jdbc.Embedded-Database-Pool.snoopenabled: "false"
  ? cloudstreamsconnection.project..kvv_2404_fedtest..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:rest2404.poolable
  : "true"
  ? cloudstreamsconnection.project..kvv_2404_fedtest..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:rest2404.minimumPoolSize
  : "1"
  ? cloudstreamsconnection.project..kvv_2404_fedtest..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:rest2404.timeoutType
  : auto
  jdbcfunc.ISInternal.failFastMode: true
  ? cloudstreamsconnection.project..kvv_2404_fedtest..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:rest2404.cn.enableSNI
  : "true"
  ? cloudstreamsconnection.project..kvv_2404_fedtest..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:rest2404.cn.socketStaleCheck
  : "true"
  jdbc.Embedded-Database-Pool.minConns: "0"
  ? cloudstreamsconnection.project..kvv_2404_fedtest..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:rest2404.maximumPoolSize
  : "10"
  ? cloudstreamsconnection.project..kvv_2404_fedtest..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:rest2404.cn.providerUrl
  : https://orgfarm-560b08beca-dev-ed.develop.my.salesforce.com
  ? cloudstreamsconnection.project..kvv_2404_fedtest..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:rest2404.cn.connectTimeout
  : "30000"
  ? artConnection.Kvv_2404_FedTestProject.project.kvv_2404_fedtest.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.mysql.connectionSettings.driverType
  : mysql
  ? artConnection.Kvv_2404_FedTestProject.project.kvv_2404_fedtest.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.mysql.connectionEnabled
  : "false"
  ? cloudstreamsconnection.project..kvv_2404_fedtest..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:rest2404.oauth.consumerId
  : 3MVG97L7PWbPq6Uy4GuKfCBdlZ2Ki3zBo1ozuvhhr4kaC8CAOPM7AlvJWTYLSJ78HYfNiPpxsko6oHNlk0DNc
  ? cloudstreamsconnection.project..kvv_2404_fedtest..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:rest2404.oauth_v20.scope
  : offline_access api refresh_token
  jdbc.SAP-TxStore-Pool.spyparms: SpyAttributes=(log=(file)logs/spy/SAP-TxStore-Pool.log;logTName=yes;timestamp=yes)
  jdbc.SAP-TxStore-Pool.minConns: "5"
  ? cloudstreamsconnection.project..kvv_2404_fedtest..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:rest2404.blockTimeout
  : "1000"
  ? cloudstreamsconnection.project..kvv_2404_fedtest..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:rest2404.oauth_v20.refreshToken
  : "{AES}EQHy/XAuhQ5jza5ZKR2OX/0iGys3kemMqXPsysWcIpFuJ9I8HHXklaBzpiiM9BsY3utrII39DrfG4cjUvqh954bfUf9dTB0T69TmZU3Rvrf2IFXDtwVYN6r7jeibWm8D"
  ? artConnection.Kvv_2404_FedTestProject.project.kvv_2404_fedtest.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.mysql.connectionSettings.dbType
  : MySQL
  ? artConnection.Kvv_2404_FedTestProject.project.kvv_2404_fedtest.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.mysql.connectionManagerSettings.expireTimeout
  : "1000"
  jdbc.SAP-TxStore-Pool.spyenabled: "false"
  jdbc.SAP-TxStore-Pool.maxConns: "10"
  ? cloudstreamsconnection.project..kvv_2404_fedtest..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:rest2404.cn.readTimeout
  : "30000"
  ? artConnection.Kvv_2404_FedTestProject.project.kvv_2404_fedtest.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.mysql.connectionManagerSettings.heartBeatInterval
  : "0"
  ? cloudstreamsconnection.project..kvv_2404_fedtest..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:rest2404.cn.enableCompression
  : "false"
  ? cloudstreamsconnection.project..kvv_2404_fedtest..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:rest2404.poolIncrementSize
  : "1"
  ? cloudstreamsconnection.project..kvv_2404_fedtest..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:rest2404.startupBackoffSecs
  : "10"
